checkpoint_path: model/facenet.ckpt
device: cpu
normalize_embeddings: true
batch_size: 32
num_workers: 2
image_size: 160
detection_threshold: 0.8
detector_weights: model/yolov8n-face.pt
detector_confidence: 0.3
